// GENERATED by gen-resort-catalog.ts — do not edit by hand.
// Rerun: bun src/server/stays/gen-resort-catalog.ts

export type ResortTier = "value" | "moderate" | "deluxe" | "villa" | "campground";

export interface ResortCatalogEntry {
  /** Numeric facility ID — joins to the resort-availability response keys. */
  id: string;
  name: string;
  slug: string;
  tier: ResortTier;
  /** Disney "resort area" (e.g. "Magic Kingdom Resort Area"), or null. */
  area: string | null;
  image: string | null;
  detailUrl: string;
}

export const RESORT_CATALOG: Array<ResortCatalogEntry> = [
  {
    id: "1",
    name: "Bay Lake Tower at Disney's Contemporary Resort",
    slug: "bay-lake-tower-at-contemporary",
    tier: "villa",
    area: "Magic Kingdom Resort Area",
    image:
      "https://cdn1.parksmedia.wdprapps.disney.com/resize/mwImage/1/1600/900/75/dam/disney-world/resorts/bay-lake-tower-at-contemporary/bay-lake-tower-contemporary-fireworks-16x9.jpg?1780333536412",
    detailUrl: "https://disneyworld.disney.go.com/resorts/bay-lake-tower-at-contemporary/",
  },
  {
    id: "80010393",
    name: "Boulder Ridge Villas at Disney's Wilderness Lodge",
    slug: "boulder-ridge-villas-at-wilderness-lodge",
    tier: "villa",
    area: "Magic Kingdom Resort Area",
    image:
      "https://cdn1.parksmedia.wdprapps.disney.com/resize/mwImage/1/1600/900/75/dam/disney-world/resorts/boulder-ridge-villas-at-wilderness-lodge/boulder-ridge-landscape-16x9.jpg?1780489306702",
    detailUrl:
      "https://disneyworld.disney.go.com/resorts/boulder-ridge-villas-at-wilderness-lodge/",
  },
  {
    id: "18390992",
    name: "Copper Creek Villas & Cabins at Disney's Wilderness Lodge",
    slug: "copper-creek-villas-and-cabins",
    tier: "villa",
    area: "Magic Kingdom Resort Area",
    image:
      "https://cdn1.parksmedia.wdprapps.disney.com/resize/mwImage/1/1600/900/75/dam/disney-world/resorts/copper-creek-villas-and-cabins/copper-creek-exterior-lake-16x9.jpg?1780489283003",
    detailUrl: "https://disneyworld.disney.go.com/resorts/copper-creek-villas-and-cabins/",
  },
  {
    id: "80010402",
    name: "Disney's All-Star Movies Resort",
    slug: "all-star-movies-resort",
    tier: "value",
    area: "Disney's Animal Kingdom Resort Area",
    image:
      "https://cdn1.parksmedia.wdprapps.disney.com/resize/mwImage/1/1600/900/75/dam/wdpro-assets/places-to-stay/all-star-movies/all-star-movies-resort-00.jpg?1780517194255",
    detailUrl: "https://disneyworld.disney.go.com/resorts/all-star-movies-resort/",
  },
  {
    id: "80010400",
    name: "Disney's All-Star Music Resort",
    slug: "all-star-music-resort",
    tier: "value",
    area: "Disney's Animal Kingdom Resort Area",
    image:
      "https://cdn1.parksmedia.wdprapps.disney.com/resize/mwImage/1/1600/900/75/dam/wdpro-assets/places-to-stay/all-star-music/all-star-music-resort-00.jpg?1779767499048",
    detailUrl: "https://disneyworld.disney.go.com/resorts/all-star-music-resort/",
  },
  {
    id: "80010401",
    name: "Disney's All-Star Sports Resort",
    slug: "all-star-sports-resort",
    tier: "value",
    area: "Disney's Animal Kingdom Resort Area",
    image:
      "https://cdn1.parksmedia.wdprapps.disney.com/resize/mwImage/1/1600/900/75/dam/wdpro-assets/places-to-stay/all-star-sports/all-star-sports-resort-00.jpg?1779767543971",
    detailUrl: "https://disneyworld.disney.go.com/resorts/all-star-sports-resort/",
  },
  {
    id: "80010395",
    name: "Disney's Animal Kingdom Lodge",
    slug: "animal-kingdom-lodge",
    tier: "deluxe",
    area: "Disney's Animal Kingdom Resort Area",
    image:
      "https://cdn1.parksmedia.wdprapps.disney.com/resize/mwImage/1/1600/900/75/dam/wdpro-assets/places-to-stay/animal-kingdom/animal-kingdom-lodge-00.jpg?1779767762297",
    detailUrl: "https://disneyworld.disney.go.com/resorts/animal-kingdom-lodge/",
  },
  {
    id: "5",
    name: "Disney's Animal Kingdom Villas - Jambo House",
    slug: "animal-kingdom-villas-jambo",
    tier: "villa",
    area: "Disney's Animal Kingdom Resort Area",
    image:
      "https://cdn1.parksmedia.wdprapps.disney.com/resize/mwImage/1/1600/900/75/dam/disney-world/resorts/animal-kingdom-villas-jambo/animal-kingdom-lodge-exterior-16x9.jpg?1779767763815",
    detailUrl: "https://disneyworld.disney.go.com/resorts/animal-kingdom-villas-jambo/",
  },
  {
    id: "273239",
    name: "Disney's Animal Kingdom Villas - Kidani Village",
    slug: "animal-kingdom-villas-kidani",
    tier: "villa",
    area: "Disney's Animal Kingdom Resort Area",
    image:
      "https://cdn1.parksmedia.wdprapps.disney.com/resize/mwImage/1/1600/900/75/dam/disney-world/resorts/animal-kingdom-villas-kidani/kidani-villiage-firepit-16x9.jpg?1780567344468",
    detailUrl: "https://disneyworld.disney.go.com/resorts/animal-kingdom-villas-kidani/",
  },
  {
    id: "80010404",
    name: "Disney's Art of Animation Resort",
    slug: "art-of-animation-resort",
    tier: "value",
    area: "Wide World of Sports Resort Area",
    image:
      "https://cdn1.parksmedia.wdprapps.disney.com/resize/mwImage/1/1600/900/75/dam/wdpro-assets/places-to-stay/art-of-animation/art-of-animation-00.jpg?1779767764376",
    detailUrl: "https://disneyworld.disney.go.com/resorts/art-of-animation-resort/",
  },
  {
    id: "80010389",
    name: "Disney's Beach Club Resort",
    slug: "beach-club-resort",
    tier: "deluxe",
    area: "EPCOT Resort Area",
    image:
      "https://cdn1.parksmedia.wdprapps.disney.com/resize/mwImage/1/1600/900/75/dam/wdpro-assets/places-to-stay/beach-club/beach-club-resort-00.jpg?1780646104502",
    detailUrl: "https://disneyworld.disney.go.com/resorts/beach-club-resort/",
  },
  {
    id: "80010407",
    name: "Disney's Beach Club Villas",
    slug: "beach-club-villas",
    tier: "villa",
    area: "EPCOT Resort Area",
    image:
      "https://cdn1.parksmedia.wdprapps.disney.com/resize/mwImage/1/1600/900/75/dam/disney-world/resorts/beach-club-villas/beach-club-villas-resort-16x9.jpg?1779768140261",
    detailUrl: "https://disneyworld.disney.go.com/resorts/beach-club-villas/",
  },
  {
    id: "80010386",
    name: "Disney's BoardWalk Inn",
    slug: "boardwalk-inn",
    tier: "deluxe",
    area: "EPCOT Resort Area",
    image:
      "https://cdn1.parksmedia.wdprapps.disney.com/resize/mwImage/1/1600/900/75/dam/wdpro-assets/gallery/resorts-fy16q2/boardwalk-inn/Overview/board-walk-inn-gallery02.jpg?1779767572794",
    detailUrl: "https://disneyworld.disney.go.com/resorts/boardwalk-inn/",
  },
  {
    id: "80010391",
    name: "Disney's BoardWalk Villas",
    slug: "boardwalk-villas",
    tier: "villa",
    area: "EPCOT Resort Area",
    image:
      "https://cdn1.parksmedia.wdprapps.disney.com/resize/mwImage/1/1600/900/75/dam/wdpro-assets/places-to-stay/boardwalk-villas/board-walk-villas-00.jpg?1779767598251",
    detailUrl: "https://disneyworld.disney.go.com/resorts/boardwalk-villas/",
  },
  {
    id: "80010399",
    name: "Disney's Caribbean Beach Resort",
    slug: "caribbean-beach-resort",
    tier: "moderate",
    area: "EPCOT Resort Area",
    image:
      "https://cdn1.parksmedia.wdprapps.disney.com/resize/mwImage/1/1600/900/75/vision-dam/digital/parks-platform/parks-global-assets/disney-world/resorts/caribbean-beach-resort/experience/0425ZM_0079OK_R1PW-5x2.jpg?2026-05-19T18:08:05+00:00",
    detailUrl: "https://disneyworld.disney.go.com/resorts/caribbean-beach-resort/",
  },
  {
    id: "80010385",
    name: "Disney's Contemporary Resort",
    slug: "contemporary-resort",
    tier: "deluxe",
    area: "Magic Kingdom Resort Area",
    image:
      "https://cdn1.parksmedia.wdprapps.disney.com/resize/mwImage/1/1600/900/75/dam/wdpro-assets/places-to-stay/contemporary/contemporary-resort-00.jpg?1780305600543",
    detailUrl: "https://disneyworld.disney.go.com/resorts/contemporary-resort/",
  },
  {
    id: "80010396",
    name: "Disney's Coronado Springs Resort",
    slug: "coronado-springs-resort",
    tier: "moderate",
    area: "Disney's Animal Kingdom Resort Area",
    image:
      "https://cdn1.parksmedia.wdprapps.disney.com/resize/mwImage/1/1600/900/75/dam/disney-world/resorts/coronado-springs-resort/coronado-tower-16x9.jpg?1779767618521",
    detailUrl: "https://disneyworld.disney.go.com/resorts/coronado-springs-resort/",
  },
  {
    id: "80010384",
    name: "Disney's Grand Floridian Resort & Spa",
    slug: "grand-floridian-resort-and-spa",
    tier: "deluxe",
    area: "Magic Kingdom Resort Area",
    image:
      "https://cdn1.parksmedia.wdprapps.disney.com/resize/mwImage/1/1600/900/75/vision-dam/digital/parks-platform/parks-global-assets/disney-world/resorts/grand-floridian/0821ZM_0873SD_JRoh_R2-16x9.jpg?2025-03-27T20:57:58+00:00",
    detailUrl: "https://disneyworld.disney.go.com/resorts/grand-floridian-resort-and-spa/",
  },
  {
    id: "80010387",
    name: "Disney's Old Key West Resort",
    slug: "old-key-west-resort",
    tier: "villa",
    area: "Disney Springs Resort Area",
    image:
      "https://cdn1.parksmedia.wdprapps.disney.com/resize/mwImage/1/1600/900/75/dam/disney-world/resorts/old-key-west-resort/old-key-west-resort-dock-16x9.jpg?1780400704342",
    detailUrl: "https://disneyworld.disney.go.com/resorts/old-key-west-resort/",
  },
  {
    id: "80010388",
    name: "Disney's Polynesian Village Resort",
    slug: "polynesian-resort",
    tier: "deluxe",
    area: "Magic Kingdom Resort Area",
    image:
      "https://cdn1.parksmedia.wdprapps.disney.com/resize/mwImage/1/1600/900/75/dam/wdpro-assets/places-to-stay/polynesian/polynesian-resort-00.jpg?1779767738104",
    detailUrl: "https://disneyworld.disney.go.com/resorts/polynesian-resort/",
  },
  {
    id: "17797842",
    name: "Disney's Polynesian Villas & Bungalows",
    slug: "polynesian-villas-bungalows",
    tier: "villa",
    area: "Magic Kingdom Resort Area",
    image:
      "https://cdn1.parksmedia.wdprapps.disney.com/resize/mwImage/1/1600/900/75/dam/wdpro-assets/places-to-stay/polynesian-villas-bungalows/polynesian-villas-bungalows-overview-01.jpg?1779767690937",
    detailUrl: "https://disneyworld.disney.go.com/resorts/polynesian-villas-bungalows/",
  },
  {
    id: "80010403",
    name: "Disney's Pop Century Resort",
    slug: "pop-century-resort",
    tier: "value",
    area: "Wide World of Sports Resort Area",
    image:
      "https://cdn1.parksmedia.wdprapps.disney.com/resize/mwImage/1/1600/900/75/dam/wdpro-assets/places-to-stay/pop-century/pop-century-resort-00.jpg?1780580973389",
    detailUrl: "https://disneyworld.disney.go.com/resorts/pop-century-resort/",
  },
  {
    id: "80010398",
    name: "Disney's Port Orleans Resort - French Quarter",
    slug: "port-orleans-resort-french-quarter",
    tier: "moderate",
    area: "Disney Springs Resort Area",
    image:
      "https://cdn1.parksmedia.wdprapps.disney.com/resize/mwImage/1/1600/900/75/vision-dam/digital/parks-platform/parks-global-assets/disney-world/resorts/port-orleans/experience/port-orleans-resort-french-quarter-gallery00-8-16x9.jpg?2026-05-05T20:09:43+00:00",
    detailUrl: "https://disneyworld.disney.go.com/resorts/port-orleans-resort-french-quarter/",
  },
  {
    id: "80010397",
    name: "Disney's Port Orleans Resort - Riverside",
    slug: "port-orleans-resort-riverside",
    tier: "moderate",
    area: "Disney Springs Resort Area",
    image:
      "https://cdn1.parksmedia.wdprapps.disney.com/resize/mwImage/1/1600/900/75/vision-dam/digital/parks-platform/parks-global-assets/disney-world/resorts/port-orleans/experience/1204ZV_0127RW-16x9.jpg?2026-05-05T20:10:37+00:00",
    detailUrl: "https://disneyworld.disney.go.com/resorts/port-orleans-resort-riverside/",
  },
  {
    id: "18995875",
    name: "Disney's Riviera Resort",
    slug: "riviera-resort",
    tier: "villa",
    area: "EPCOT Resort Area",
    image:
      "https://cdn1.parksmedia.wdprapps.disney.com/resize/mwImage/1/1600/900/75/dam/disney-world/resorts/riviera-resort/overview/riviera-enterance-16x9.jpg?1779767463819",
    detailUrl: "https://disneyworld.disney.go.com/resorts/riviera-resort/",
  },
  {
    id: "80010383",
    name: "Disney's Saratoga Springs Resort & Spa",
    slug: "saratoga-springs-resort-and-spa",
    tier: "villa",
    area: "Disney Springs Resort Area",
    image:
      "https://cdn1.parksmedia.wdprapps.disney.com/resize/mwImage/1/1600/900/75/dam/disney-world/resorts/saratoga-springs-resort-and-spa/saratoga-springs-water-island-16x9.jpg?1779767866035",
    detailUrl: "https://disneyworld.disney.go.com/resorts/saratoga-springs-resort-and-spa/",
  },
  {
    id: "80010394",
    name: "Disney's Wilderness Lodge",
    slug: "wilderness-lodge-resort",
    tier: "deluxe",
    area: "Magic Kingdom Resort Area",
    image:
      "https://cdn1.parksmedia.wdprapps.disney.com/resize/mwImage/1/1600/900/75/dam/wdpro-assets/places-to-stay/wilderness-lodge/wilderness-lodge-resort-00.jpg?1780489474144",
    detailUrl: "https://disneyworld.disney.go.com/resorts/wilderness-lodge-resort/",
  },
  {
    id: "80010390",
    name: "Disney's Yacht Club Resort",
    slug: "yacht-club-resort",
    tier: "deluxe",
    area: "EPCOT Resort Area",
    image:
      "https://cdn1.parksmedia.wdprapps.disney.com/resize/mwImage/1/1600/900/75/dam/wdpro-assets/places-to-stay/yacht-club-resort/yacht-club-resort-00.jpg?1779768080648",
    detailUrl: "https://disneyworld.disney.go.com/resorts/yacht-club-resort/",
  },
  {
    id: "411930769",
    name: "The Cabins at Disney's Fort Wilderness Resort",
    slug: "cabins-at-fort-wilderness-resort",
    tier: "villa",
    area: "Magic Kingdom Resort Area",
    image:
      "https://cdn1.parksmedia.wdprapps.disney.com/resize/mwImage/1/1600/900/75/dam/wdpro-assets/places-to-stay/cabins-at-fort-wilderness/cabins-at-fort-wilderness-resort-00.jpg",
    detailUrl: "https://disneyworld.disney.go.com/resorts/cabins-at-fort-wilderness-resort/",
  },
  {
    id: "80010392",
    name: "The Campsites at Disney's Fort Wilderness Resort",
    slug: "campsites-at-fort-wilderness-resort",
    tier: "campground",
    area: "Magic Kingdom Resort Area",
    image:
      "https://cdn1.parksmedia.wdprapps.disney.com/resize/mwImage/1/1600/900/75/dam/wdpro-assets/places-to-stay/campsites-at-fort-wilderness/campsites-at-fort-wilderness-resort-00.jpg?1779888485158",
    detailUrl: "https://disneyworld.disney.go.com/resorts/campsites-at-fort-wilderness-resort/",
  },
  {
    id: "16491822",
    name: "The Villas at Disney's Grand Floridian Resort & Spa",
    slug: "villas-at-grand-floridian-resort-and-spa",
    tier: "villa",
    area: "Magic Kingdom Resort Area",
    image:
      "https://cdn1.parksmedia.wdprapps.disney.com/resize/mwImage/1/1600/900/75/dam/disney-world/resorts/grand-floridian-resort-and-spa/grand-floridian-exterior-lake-16x9.jpg?1779984138193",
    detailUrl:
      "https://disneyworld.disney.go.com/resorts/villas-at-grand-floridian-resort-and-spa/",
  },
  {
    id: "80069788",
    name: "Walt Disney World Dolphin Hotel",
    slug: "dolphin-hotel",
    tier: "deluxe",
    area: "EPCOT Resort Area",
    image:
      "https://cdn1.parksmedia.wdprapps.disney.com/resize/mwImage/1/1600/900/75/dam/wdpro-assets/places-to-stay/dolphin/dolphin-resort-00.jpg?1771929265571",
    detailUrl: "https://disneyworld.disney.go.com/resorts/dolphin-hotel/",
  },
  {
    id: "80069789",
    name: "Walt Disney World Swan Hotel",
    slug: "swan-hotel",
    tier: "deluxe",
    area: "EPCOT Resort Area",
    image:
      "https://cdn1.parksmedia.wdprapps.disney.com/resize/mwImage/1/1600/900/75/dam/wdpro-assets/places-to-stay/swan-resort/swan-resort-00.jpg?1776340761827",
    detailUrl: "https://disneyworld.disney.go.com/resorts/swan-hotel/",
  },
  {
    id: "19621562",
    name: "Walt Disney World Swan Reserve",
    slug: "swan-reserve",
    tier: "deluxe",
    area: "EPCOT Resort Area",
    image:
      "https://cdn1.parksmedia.wdprapps.disney.com/resize/mwImage/1/1600/900/75/vision-dam/digital/parks-platform/parks-global-assets/disney-world/resorts/swan-and-dolphin/A176-Exterior-2-16x9.jpg?2022-02-18T19:49:36+00:00",
    detailUrl: "https://disneyworld.disney.go.com/resorts/swan-reserve/",
  },
];

export const RESORT_BY_ID: Map<string, ResortCatalogEntry> = new Map(
  RESORT_CATALOG.map((r) => [r.id, r]),
);
