/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TicketsRouteImport } from './routes/tickets'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DisclaimersRouteImport } from './routes/disclaimers'
import { Route as DiningRouteImport } from './routes/dining'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiTrpcSplatRouteImport } from './routes/api.trpc.$'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'

const TicketsRoute = TicketsRouteImport.update({
  id: '/tickets',
  path: '/tickets',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DisclaimersRoute = DisclaimersRouteImport.update({
  id: '/disclaimers',
  path: '/disclaimers',
  getParentRoute: () => rootRouteImport,
} as any)
const DiningRoute = DiningRouteImport.update({
  id: '/dining',
  path: '/dining',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTrpcSplatRoute = ApiTrpcSplatRouteImport.update({
  id: '/api/trpc/$',
  path: '/api/trpc/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dining': typeof DiningRoute
  '/disclaimers': typeof DisclaimersRoute
  '/login': typeof LoginRoute
  '/tickets': typeof TicketsRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/trpc/$': typeof ApiTrpcSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dining': typeof DiningRoute
  '/disclaimers': typeof DisclaimersRoute
  '/login': typeof LoginRoute
  '/tickets': typeof TicketsRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/trpc/$': typeof ApiTrpcSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dining': typeof DiningRoute
  '/disclaimers': typeof DisclaimersRoute
  '/login': typeof LoginRoute
  '/tickets': typeof TicketsRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/trpc/$': typeof ApiTrpcSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dining'
    | '/disclaimers'
    | '/login'
    | '/tickets'
    | '/api/auth/$'
    | '/api/trpc/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dining'
    | '/disclaimers'
    | '/login'
    | '/tickets'
    | '/api/auth/$'
    | '/api/trpc/$'
  id:
    | '__root__'
    | '/'
    | '/dining'
    | '/disclaimers'
    | '/login'
    | '/tickets'
    | '/api/auth/$'
    | '/api/trpc/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DiningRoute: typeof DiningRoute
  DisclaimersRoute: typeof DisclaimersRoute
  LoginRoute: typeof LoginRoute
  TicketsRoute: typeof TicketsRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiTrpcSplatRoute: typeof ApiTrpcSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tickets': {
      id: '/tickets'
      path: '/tickets'
      fullPath: '/tickets'
      preLoaderRoute: typeof TicketsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/disclaimers': {
      id: '/disclaimers'
      path: '/disclaimers'
      fullPath: '/disclaimers'
      preLoaderRoute: typeof DisclaimersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dining': {
      id: '/dining'
      path: '/dining'
      fullPath: '/dining'
      preLoaderRoute: typeof DiningRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/trpc/$': {
      id: '/api/trpc/$'
      path: '/api/trpc/$'
      fullPath: '/api/trpc/$'
      preLoaderRoute: typeof ApiTrpcSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DiningRoute: DiningRoute,
  DisclaimersRoute: DisclaimersRoute,
  LoginRoute: LoginRoute,
  TicketsRoute: TicketsRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiTrpcSplatRoute: ApiTrpcSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
